//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising_Zone
    {
        public int ID { get; set; }
        public string PageAscii { get; set; }
        public string Page { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool Show { get; set; }
        public string LanguageId { get; set; }
    }
}
