//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckAccount
    {
        public CheckAccount()
        {
            this.PaymentAccounts = new HashSet<PaymentAccount>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<decimal> PricePV { get; set; }
    
        public virtual ICollection<PaymentAccount> PaymentAccounts { get; set; }
    }
}
