//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CayMois = new HashSet<CayMoi>();
            this.CheckLogins = new HashSet<CheckLogin>();
            this.Custome_RankCustomer = new HashSet<Custome_RankCustomer>();
            this.Custome_RankCustomerHistory = new HashSet<Custome_RankCustomerHistory>();
            this.HistoryAwardLoops = new HashSet<HistoryAwardLoop>();
            this.HistoryAwards = new HashSet<HistoryAward>();
            this.HistoryAwaysMaRois = new HashSet<HistoryAwaysMaRoi>();
            this.HistoryUpRanks = new HashSet<HistoryUpRank>();
            this.Orders = new HashSet<Order>();
            this.RankNow_BackUp = new HashSet<RankNow_BackUp>();
            this.RankNows = new HashSet<RankNow>();
            this.RegisteredAgencies = new HashSet<RegisteredAgency>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PeoplesIdentity { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string AddressCompany { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public string NameCompany { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> CustomerAvatarID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public string ListCustomerId { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProvincialAgencyID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> IsIndex { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> IdentityType { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public Nullable<bool> IsDistributor { get; set; }
        public string PeoplesIdentityReward { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
        public string ListCustomerId2 { get; set; }
        public Nullable<int> Level2 { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> LastActivityDateUtc { get; set; }
        public string SomeBank { get; set; }
        public Nullable<int> NumberVourcher { get; set; }
        public Nullable<int> MonthVourcher { get; set; }
        public Nullable<System.DateTime> DateVourcher { get; set; }
    
        public virtual ICollection<CayMoi> CayMois { get; set; }
        public virtual ICollection<CheckLogin> CheckLogins { get; set; }
        public virtual ICollection<Custome_RankCustomer> Custome_RankCustomer { get; set; }
        public virtual ICollection<Custome_RankCustomerHistory> Custome_RankCustomerHistory { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual ProvincialAgency ProvincialAgency { get; set; }
        public virtual ICollection<HistoryAwardLoop> HistoryAwardLoops { get; set; }
        public virtual ICollection<HistoryAward> HistoryAwards { get; set; }
        public virtual ICollection<HistoryAwaysMaRoi> HistoryAwaysMaRois { get; set; }
        public virtual ICollection<HistoryUpRank> HistoryUpRanks { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<RankNow_BackUp> RankNow_BackUp { get; set; }
        public virtual ICollection<RankNow> RankNows { get; set; }
        public virtual ICollection<RegisteredAgency> RegisteredAgencies { get; set; }
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
