//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custome_RankCustomerHistory
    {
        public int ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> RankCustomerId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsCustomerType { get; set; }
        public Nullable<decimal> PricePV { get; set; }
        public string Code { get; set; }
        public Nullable<int> TypeCustomer { get; set; }
        public string ListCustomerId { get; set; }
        public Nullable<int> ProvincialAgencyID { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> TotalAgency { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProvincialAgency ProvincialAgency { get; set; }
        public virtual RankCustome RankCustome { get; set; }
    }
}
