//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custome_RankCustomer
    {
        public Custome_RankCustomer()
        {
            this.HistoryAwardLoops = new HashSet<HistoryAwardLoop>();
            this.HistoryAwaysMaRois = new HashSet<HistoryAwaysMaRoi>();
            this.Shop_Order_Product = new HashSet<Shop_Order_Product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> RankCustomerId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<decimal> PricePV { get; set; }
        public string ListCustomerId { get; set; }
        public Nullable<int> ProvincialAgencyID { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Goi { get; set; }
        public string UserCreated { get; set; }
        public string Note { get; set; }
        public Nullable<int> VourcherID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProvincialAgency ProvincialAgency { get; set; }
        public virtual RankCustome RankCustome { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual ICollection<HistoryAwardLoop> HistoryAwardLoops { get; set; }
        public virtual ICollection<HistoryAwaysMaRoi> HistoryAwaysMaRois { get; set; }
        public virtual ICollection<Shop_Order_Product> Shop_Order_Product { get; set; }
    }
}
