//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor
    {
        public Distributor()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Avartar { get; set; }
        public string Address { get; set; }
        public string PeoplesIdentity { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Mobile { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string TaxCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> PicturePeoplesIdentity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string CodeContract { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<int> PicturePeoplesIdentity2 { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
        public Nullable<int> ProvincialAgencyID { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual Gallery_Picture Gallery_Picture1 { get; set; }
        public virtual ProvincialAgency ProvincialAgency { get; set; }
        public virtual ProvincialAgency ProvincialAgency1 { get; set; }
        public virtual Gallery_Picture Gallery_Picture2 { get; set; }
        public virtual Gallery_Picture Gallery_Picture3 { get; set; }
    }
}
