//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_Picture
    {
        public Gallery_Picture()
        {
            this.Customers = new HashSet<Customer>();
            this.Distributors = new HashSet<Distributor>();
            this.Distributors1 = new HashSet<Distributor>();
            this.Distributors2 = new HashSet<Distributor>();
            this.Distributors3 = new HashSet<Distributor>();
            this.Languages = new HashSet<Language>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string Folder { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string LanguageId { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Distributor> Distributors { get; set; }
        public virtual ICollection<Distributor> Distributors1 { get; set; }
        public virtual ICollection<Distributor> Distributors2 { get; set; }
        public virtual ICollection<Distributor> Distributors3 { get; set; }
        public virtual ICollection<Language> Languages { get; set; }
    }
}
