//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAward
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CheckAwardkId { get; set; }
        public Nullable<decimal> PricePV { get; set; }
        public Nullable<int> CustomerRankId { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> IsRank { get; set; }
    
        public virtual CheckAward CheckAward { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
