//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAwaysMaRoi
    {
        public int ID { get; set; }
        public Nullable<int> CustomeRankCustomerId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> LevelRank { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Custome_RankCustomer Custome_RankCustomer { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
