//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAwardLoop
    {
        public int ID { get; set; }
        public int CustomerRankID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserDeleted { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsAwards1 { get; set; }
        public Nullable<bool> IsAwards2 { get; set; }
        public Nullable<bool> IsAwards3 { get; set; }
        public Nullable<bool> IsAwards4 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards1 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards2 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards3 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards4 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards5 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards6 { get; set; }
        public Nullable<System.DateTime> DateCreatedAwards7 { get; set; }
        public Nullable<bool> IsAwards5 { get; set; }
        public Nullable<bool> IsAwards6 { get; set; }
        public Nullable<bool> IsAwards7 { get; set; }
    
        public virtual Custome_RankCustomer Custome_RankCustomer { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
