//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleControl
    {
        public int Id { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string FileName { get; set; }
        public string ControlID { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> PortalID { get; set; }
    }
}
