//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAccount
    {
        public PaymentAccount()
        {
            this.CheckAccounts = new HashSet<CheckAccount>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string NameCustomer { get; set; }
        public string AddressAccount { get; set; }
        public Nullable<decimal> PricePV { get; set; }
    
        public virtual ICollection<CheckAccount> CheckAccounts { get; set; }
    }
}
