//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvincialAgency
    {
        public ProvincialAgency()
        {
            this.Custome_RankCustomer = new HashSet<Custome_RankCustomer>();
            this.Custome_RankCustomerHistory = new HashSet<Custome_RankCustomerHistory>();
            this.Customers = new HashSet<Customer>();
            this.Distributors = new HashSet<Distributor>();
            this.Distributors1 = new HashSet<Distributor>();
            this.RegisteredAgencies = new HashSet<RegisteredAgency>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string AccountNumber { get; set; }
        public string InformationAccount { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
    
        public virtual ICollection<Custome_RankCustomer> Custome_RankCustomer { get; set; }
        public virtual ICollection<Custome_RankCustomerHistory> Custome_RankCustomerHistory { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Distributor> Distributors { get; set; }
        public virtual ICollection<Distributor> Distributors1 { get; set; }
        public virtual System_City System_City { get; set; }
        public virtual System_District System_District { get; set; }
        public virtual ICollection<RegisteredAgency> RegisteredAgencies { get; set; }
    }
}
