//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankNow
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> PricePVUser { get; set; }
        public Nullable<int> UserId1 { get; set; }
        public Nullable<decimal> PricePVUser1 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> PVUser { get; set; }
        public Nullable<decimal> PVUser1 { get; set; }
        public Nullable<int> ActiveRank { get; set; }
        public Nullable<decimal> PVMonth { get; set; }
        public Nullable<decimal> PVMonth1 { get; set; }
        public Nullable<bool> IsAward { get; set; }
        public Nullable<int> CheckLimit { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<int> CustomerRankId { get; set; }
        public Nullable<decimal> PricePVX { get; set; }
        public Nullable<decimal> PricePVNow { get; set; }
        public Nullable<decimal> PVOld { get; set; }
        public Nullable<decimal> PVOld1 { get; set; }
        public Nullable<bool> IsPay { get; set; }
        public Nullable<bool> IsPay40 { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
