//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankCustome
    {
        public RankCustome()
        {
            this.Custome_RankCustomer = new HashSet<Custome_RankCustomer>();
            this.Custome_RankCustomerHistory = new HashSet<Custome_RankCustomerHistory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> Percent { get; set; }
        public string Color { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<decimal> PricePV { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<Custome_RankCustomer> Custome_RankCustomer { get; set; }
        public virtual ICollection<Custome_RankCustomerHistory> Custome_RankCustomerHistory { get; set; }
    }
}
