//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Order_Product
    {
        public int ID { get; set; }
        public int CustomeRankCustomerId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Custome_RankCustomer Custome_RankCustomer { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
    }
}
