//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCard
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string CardNumber { get; set; }
        public string AccountName { get; set; }
        public int Balance { get; set; }
        public string CardTypeCode { get; set; }
        public Nullable<bool> IsRelease { get; set; }
        public Nullable<bool> IsLockCard { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
        public string Temp4 { get; set; }
        public string Temp5 { get; set; }
        public bool IsEdit { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
