//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public Voucher()
        {
            this.Custome_RankCustomer = new HashSet<Custome_RankCustomer>();
        }
    
        public int ID { get; set; }
        public string CustomerUserName { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual ICollection<Custome_RankCustomer> Custome_RankCustomer { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
